### PR TITLE
casas_gis_old: initial file organization restructuring

### PR DESCRIPTION
**Pull request by neteler**
- cleanup in a way that files are clustered in subdirectories.
- avoid white space in filenames
- fix not/executable bits (`chmod`) on scripts and text files

TODO: Likely paths still need to be updated (to be done in a separate PR during planned update of scripts, i.e. porting to GRASS GIS 8).

The following duplicates have been identified (based on `md5sum` checks):

```
#rm ./outfiles/turbo_string.sh
#rm ./outfiles/turbo_string.txt

#rm ./outfiles/africa_cassava_test_3/defaultColorRule
#rm ./palettes/defaultColorRule
#rm ./palettes/defaultColorRule_luigi_nasa_with_white_bottom
#rm ./palettes/defaultColorRule_nasa_white_bottom.txt

#rm ./casas/scripts/usa_backup_2019-09-03
#rm ./casas/scripts/usa_backup_2019-09-04
#rm ./casas/scripts/usa_backup_2020-06-05
#rm ./casas/scripts/usa\ -\ Copy

#rm ./palettes/greyColorRule
#rm ./palettes/greyColorRule_backup

#rm ./outfiles/boxplotOutliersForMapping\ -\ Copy.R
#rm ./outfiles/boxplotOutliersForMapping.R

#rm ./outfiles/africa_cassava_test_3/data/Plants_14Jan23_Avg.txt
#rm ./outfiles/Plants_14Jan23_Avg.txt

#rm ./outfiles/swd_ita_spline_morethan5
#rm ./palettes/defaultColorRule_nasa

#rm ./casas/scripts/EurMedGrape_backup_2019-09-03
#rm ./casas/scripts/EurMedGrape_backup_2019-09-04
#rm ./casas/scripts/EurMedGrape_backup_2020-06-05
```

Only one of each dupe-group may remain.

### CODE REVIEW

**Comment by luisponti** [comment]
```bash
rm ./outfiles/turbo_string.sh
#rm ./outfiles/turbo_string.txt

# This one is part of sample output from the GIS script
# as the scripts usually save the color rule used
#rm ./outfiles/africa_cassava_test_3/defaultColorRule

# This one is the actual color rule
#rm ./palettes/defaultColorRule

#rm ./palettes/defaultColorRule_luigi_nasa_with_white_bottom
#rm ./palettes/defaultColorRule_nasa_white_bottom.txt

rm ./casas/scripts/usa_backup_2019-09-03
rm ./casas/scripts/usa_backup_2019-09-04
rm ./casas/scripts/usa_backup_2020-06-05

# Not sure what the -\ Copy part means
#rm ./casas/scripts/usa\ -\ Copy

#rm ./palettes/greyColorRule
rm ./palettes/greyColorRule_backup

# I think this one should be removed but still
# not sure what the -\ Copy part means
rm ./outfiles/boxplotOutliersForMapping\ -\ Copy.R
#rm ./outfiles/boxplotOutliersForMapping.R

#rm ./outfiles/africa_cassava_test_3/data/Plants_14Jan23_Avg.txt
rm ./outfiles/Plants_14Jan23_Avg.txt

rm ./outfiles/swd_ita_spline_morethan5
#rm ./palettes/defaultColorRule_nasa

rm ./casas/scripts/EurMedGrape_backup_2019-09-03
rm ./casas/scripts/EurMedGrape_backup_2019-09-04
rm ./casas/scripts/EurMedGrape_backup_2020-06-05
```

**Comment by neteler** [comment]
> What does the `-\ Copy` part mean in some of the paths?

That's the name of the file:
https://github.com/casasglobal-org/casas-gis/blob/main/casas_gis_old/outfiles/boxplotOutliersForMapping%20-%20Copy.R
(the `\` is the space character escaping)

**Comment by neteler** [comment]
Suggested files deleted in 9804921f022c2dc1ac8f837b4cdaabc9c1cd0ee6

**Comment by luisponti** [comment]
> > What does the `-\ Copy` part mean in some of the paths?
> 
> That's the name of the file: https://github.com/casasglobal-org/casas-gis/blob/main/casas_gis_old/outfiles/boxplotOutliersForMapping%20-%20Copy.R (the `\` is the space character escaping)

Not sure how files with “Copy” at the end of the name. Probably some Windows weirdness. They may however be deleted.

**Pull request merged**
